##
##  Makefile -- Build procedure for sample lttng Apache module
##  Autogenerated via ``apxs -n lttng -g''.
##

ap_basedir=/usr/share/apache2
builddir=.
top_srcdir=$(ap_basedir)
top_builddir=$(ap_basedir)
include $(ap_basedir)/build/special.mk

#   the used tools
APXS=$(ap_basedir)/bin/apxs
APACHECTL=$(ap_basedir)/bin/apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
LIBS=-ldl -llttng-ust

#   the default target
all: local-shared-build

install: install-modules-yes

clean:
	-rm -f mod_lttng.o mod_lttng.lo mod_lttng.slo mod_lttng.la
